version: '3'

services:

  java:
    image: openjdk:22
    container_name: favorites
    restart: always
    working_dir: /app
    tty: true
    volumes:
      - ../:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      favorite-dev:

  db:
    image: postgres:16
    container_name: favorite_dev_postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      favorite-dev:

networks:
  favorite-dev:
    name: favorite-dev
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"