version: '3.8'

services:

  java:
    image: openjdk:17
    container_name: favorites
    restart: always
    working_dir: /app
    tty: true
    volumes:
      - ../:/app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    build: .
    image: postgres:16
    container_name: favorite_dev_postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
    # ローカルのpostgres/initディレクトリをコンテナの/docker-entrypointdb.dにマウント
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
      
volumes:
  db-store:
